// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaqnibfbdhbxfwgasgky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhcW5pYmZiZGhieGZ3Z2FzZ2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzE3ODIsImV4cCI6MjA3MDA0Nzc4Mn0.LaLX3mKyAWK64Kj6gQplbFtg9Ev8acwsVtS8mqtrZiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
