// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdludmhyfezaftriyuhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkbHVkbWh5ZmV6YWZ0cml5dWhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDU1MjQsImV4cCI6MjA2NTk4MTUyNH0.9gZxj0tXjX51OjjXYGSN3h9gXkds-WI77yImPtoLKyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});